# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_app:
    working_directory: ~/ESAC-Dashboard

    docker:
      - image: circleci/node:14.15.4
        #auth:
        #  username: mydockerhub-user
        #  password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && npm test
      - run: cd server && npm install
      - run: cd server && npm test

# Orchestrate our job run sequence
workflows:
  build_and_test_app:
    jobs:
      - build_app
